tunnel: 63090a6f-b69a-457f-ac79-279f7c5c8fae
credentials-file: /etc/cloudflared/63090a6f-b69a-457f-ac79-279f7c5c8fae.json

ingress:
  # Public hostname -> local service
  - hostname: api.kshitij.space
    service: http://api:8000

  # (optional) expose FastAPI docs directly at a subpath, if you want
  # - hostname: api.kshitij.space
  #   service: http://localhost:8000
  #   path: /docs

  # Catch-all: anything not matched above returns 404
  - service: http_status:404

