FROM python:3.12-slim

WORKDIR /api

RUN pip install uv

COPY pyproject.toml .
COPY uv.lock .
RUN uv pip install -r pyproject.toml --system --compile-bytecode

COPY api/migrations/ ./migrations
COPY api/migrations/alembic.ini ./alembic.ini
COPY api/app/ ./app

# Set PYTHONPATH to include the current directory so imports work
ENV PYTHONPATH=/api 


#CMD ["alembic", "revision", "-m" ,"Create employee table"]
#CMD ["alembic", "upgrade", "head"]