# Local Fly.io Simulation Configuration
# This file mirrors fly.toml settings for local development
# Use with: flyctl local

app = 'data-hygiene-toolkit-local'
primary_region = 'local'

[build]
# Uses local Dockerfile (same as production)

[deploy]
  # For local simulation, we can skip migrations or run them separately
  # release_command = 'alembic upgrade head'

[env]
  PORT = '8000'
  ENVIRONMENT = 'local-prod-sim'

[http_service]
  internal_port = 8000
  force_https = false  # Local doesn't need HTTPS enforcement
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1  # Keep 1 running for local dev
  max_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '30s'
    method = 'GET'
    path = '/'

[[vm]]
  # Match production constraints for testing
  memory = '256mb'  # Same as production
  cpu_kind = 'shared'
  cpus = 1

# Note: Local volume mounts are handled via docker-compose
# [mounts]
#   source = "data_volume"
#   destination = "/api/data"
#   initial_size = "1gb"

# Local development overrides
[experimental]
  # Enable any Fly.io experimental features you want to test locally
