"""add_advanced_features_tables

Revision ID: bf6bfa17bc31
Revises: 1903bb90c0fb
Create Date: 2025-10-16 16:15:41.192738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf6bfa17bc31'
down_revision: Union[str, None] = '1903bb90c0fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_templates',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('category', sa.String(), nullable=False),
                    sa.Column('template_kind', sa.Enum('missing_data', 'standardization', 'value_list', 'length_range', 'cross_field', 'char_restriction',
                                                       'regex', 'custom', 'statistical_outlier', 'distribution_check', 'correlation_validation', 'ml_anomaly', name='rulekind'), nullable=False),
                    sa.Column('template_params', sa.Text(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('usage_count', sa.Integer(), nullable=True),
                    sa.Column('created_by', sa.String(), nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_rule_templates_category'),
                    'rule_templates', ['category'], unique=False)
    op.create_index(op.f('ix_rule_templates_id'),
                    'rule_templates', ['id'], unique=False)
    op.create_index(op.f('ix_rule_templates_name'),
                    'rule_templates', ['name'], unique=False)
    op.create_table('ml_models',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('model_type', sa.String(), nullable=False),
                    sa.Column('version', sa.String(), nullable=False),
                    sa.Column('model_path', sa.String(), nullable=True),
                    sa.Column('model_metadata', sa.Text(), nullable=True),
                    sa.Column('training_dataset_id',
                              sa.String(), nullable=True),
                    sa.Column('training_metrics', sa.Text(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('created_by', sa.String(), nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
                    sa.ForeignKeyConstraint(
                        ['training_dataset_id'], ['datasets.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_ml_models_id'), 'ml_models', ['id'], unique=False)
    op.create_index(op.f('ix_ml_models_name'),
                    'ml_models', ['name'], unique=False)
    op.create_table('rule_suggestions',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('dataset_id', sa.String(), nullable=False),
                    sa.Column('template_id', sa.String(), nullable=True),
                    sa.Column('suggested_rule_name',
                              sa.String(), nullable=False),
                    sa.Column('suggested_params', sa.Text(), nullable=True),
                    sa.Column('confidence_score', sa.Integer(), nullable=True),
                    sa.Column('suggestion_type', sa.String(), nullable=True),
                    sa.Column('reasoning', sa.Text(), nullable=True),
                    sa.Column('is_applied', sa.Boolean(), nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('applied_at', postgresql.TIMESTAMP(
                        timezone=True), nullable=True),
                    sa.Column('applied_by', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['applied_by'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
                    sa.ForeignKeyConstraint(
                        ['template_id'], ['rule_templates.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_rule_suggestions_id'),
                    'rule_suggestions', ['id'], unique=False)
    op.create_table('dataset_profiles',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('dataset_version_id',
                              sa.String(), nullable=False),
                    sa.Column('profile_summary', sa.Text(), nullable=True),
                    sa.Column('column_profiles', sa.Text(), nullable=True),
                    sa.Column('data_quality_score',
                              sa.Integer(), nullable=True),
                    sa.Column('recommendations', sa.Text(), nullable=True),
                    sa.Column('profiling_version', sa.String(), nullable=True),
                    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['dataset_version_id'], [
                        'dataset_versions.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('dataset_version_id')
                    )
    op.create_index(op.f('ix_dataset_profiles_id'),
                    'dataset_profiles', ['id'], unique=False)
    op.create_table('statistical_metrics',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('dataset_version_id',
                              sa.String(), nullable=False),
                    sa.Column('column_name', sa.String(), nullable=False),
                    sa.Column('metric_type', sa.String(), nullable=False),
                    sa.Column('metric_name', sa.String(), nullable=False),
                    sa.Column('metric_value', sa.Integer(), nullable=True),
                    sa.Column('additional_data', sa.Text(), nullable=True),
                    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['dataset_version_id'], [
                        'dataset_versions.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_statistical_metrics_id'),
                    'statistical_metrics', ['id'], unique=False)
    op.create_table('anomaly_scores',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('execution_id', sa.String(), nullable=False),
                    sa.Column('model_id', sa.String(), nullable=False),
                    sa.Column('row_index', sa.Integer(), nullable=False),
                    sa.Column('anomaly_score', sa.Integer(), nullable=False),
                    sa.Column('features_used', sa.Text(), nullable=True),
                    sa.Column('feature_values', sa.Text(), nullable=True),
                    sa.Column('threshold_used', sa.Integer(), nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['execution_id'], ['executions.id'], ),
                    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_anomaly_scores_id'),
                    'anomaly_scores', ['id'], unique=False)
    op.create_table('debug_sessions',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('execution_id', sa.String(), nullable=False),
                    sa.Column('session_name', sa.String(), nullable=False),
                    sa.Column('debug_data', sa.Text(), nullable=True),
                    sa.Column('breakpoints', sa.Text(), nullable=True),
                    sa.Column('variable_snapshots', sa.Text(), nullable=True),
                    sa.Column('created_by', sa.String(), nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
                    sa.ForeignKeyConstraint(
                        ['execution_id'], ['executions.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_debug_sessions_id'),
                    'debug_sessions', ['id'], unique=False)
    op.alter_column('data_quality_metrics', 'dqi',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    type_=sa.Integer(),
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('data_quality_metrics', 'clean_rows_pct',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    type_=sa.Integer(),
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('data_quality_metrics', 'hybrid',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    type_=sa.Integer(),
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('data_quality_metrics', 'computed_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True,
                    existing_server_default=sa.text('now()'))
    op.alter_column('data_quality_metrics', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True,
                    existing_server_default=sa.text('now()'))
    op.alter_column('data_quality_metrics', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True,
                    existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_data_quality_metrics_dataset_version_id'),
                  table_name='data_quality_metrics')
    op.drop_index(op.f('ix_data_quality_metrics_execution_id'),
                  table_name='data_quality_metrics')
    op.create_index(op.f('ix_data_quality_metrics_id'),
                    'data_quality_metrics', ['id'], unique=False)
    op.create_unique_constraint(None, 'data_quality_metrics', ['execution_id'])
    op.drop_index(op.f('ix_dataset_versions_parent_version_id'),
                  table_name='dataset_versions')
    op.drop_index(op.f('ix_dataset_versions_source'),
                  table_name='dataset_versions')
    op.drop_index(op.f('ix_fixes_applied_in_version_id'), table_name='fixes')
    op.drop_index(op.f('ix_rules_dependency_group'), table_name='rules')
    op.drop_index(op.f('ix_rules_execution_order'), table_name='rules')
    op.drop_index(op.f('ix_rules_name_is_latest_unique'),
                  table_name='rules', postgresql_where='(is_latest = true)')
    op.drop_index(op.f('ix_rules_priority'), table_name='rules')
    op.drop_constraint(op.f('fk_rules_parent_rule_id'),
                       'rules', type_='foreignkey')
    op.drop_constraint(op.f('fk_rules_rule_family_id'),
                       'rules', type_='foreignkey')
    op.create_foreign_key(None, 'rules', 'rules', ['rule_family_id'], ['id'])
    op.create_foreign_key(None, 'rules', 'rules', ['parent_rule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rules', type_='foreignkey')
    op.drop_constraint(None, 'rules', type_='foreignkey')
    op.create_foreign_key(op.f('fk_rules_rule_family_id'), 'rules', 'rules', [
                          'rule_family_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_rules_parent_rule_id'), 'rules', 'rules', [
                          'parent_rule_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_rules_priority'), 'rules',
                    ['priority'], unique=False)
    op.create_index(op.f('ix_rules_name_is_latest_unique'), 'rules', [
                    'name'], unique=True, postgresql_where='(is_latest = true)')
    op.create_index(op.f('ix_rules_execution_order'), 'rules',
                    ['execution_order'], unique=False)
    op.create_index(op.f('ix_rules_dependency_group'), 'rules',
                    ['dependency_group'], unique=False)
    op.create_index(op.f('ix_fixes_applied_in_version_id'),
                    'fixes', ['applied_in_version_id'], unique=False)
    op.create_index(op.f('ix_dataset_versions_source'),
                    'dataset_versions', ['source'], unique=False)
    op.create_index(op.f('ix_dataset_versions_parent_version_id'),
                    'dataset_versions', ['parent_version_id'], unique=False)
    op.drop_constraint(None, 'data_quality_metrics', type_='unique')
    op.drop_index(op.f('ix_data_quality_metrics_id'),
                  table_name='data_quality_metrics')
    op.create_index(op.f('ix_data_quality_metrics_execution_id'),
                    'data_quality_metrics', ['execution_id'], unique=True)
    op.create_index(op.f('ix_data_quality_metrics_dataset_version_id'),
                    'data_quality_metrics', ['dataset_version_id'], unique=False)
    op.alter_column('data_quality_metrics', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False,
                    existing_server_default=sa.text('now()'))
    op.alter_column('data_quality_metrics', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False,
                    existing_server_default=sa.text('now()'))
    op.alter_column('data_quality_metrics', 'computed_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False,
                    existing_server_default=sa.text('now()'))
    op.alter_column('data_quality_metrics', 'hybrid',
                    existing_type=sa.Integer(),
                    type_=sa.DOUBLE_PRECISION(precision=53),
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('data_quality_metrics', 'clean_rows_pct',
                    existing_type=sa.Integer(),
                    type_=sa.DOUBLE_PRECISION(precision=53),
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('data_quality_metrics', 'dqi',
                    existing_type=sa.Integer(),
                    type_=sa.DOUBLE_PRECISION(precision=53),
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'::double precision"))
    op.drop_index(op.f('ix_debug_sessions_id'), table_name='debug_sessions')
    op.drop_table('debug_sessions')
    op.drop_index(op.f('ix_anomaly_scores_id'), table_name='anomaly_scores')
    op.drop_table('anomaly_scores')
    op.drop_index(op.f('ix_statistical_metrics_id'),
                  table_name='statistical_metrics')
    op.drop_table('statistical_metrics')
    op.drop_index(op.f('ix_dataset_profiles_id'),
                  table_name='dataset_profiles')
    op.drop_table('dataset_profiles')
    op.drop_index(op.f('ix_rule_suggestions_id'),
                  table_name='rule_suggestions')
    op.drop_table('rule_suggestions')
    op.drop_index(op.f('ix_ml_models_name'), table_name='ml_models')
    op.drop_index(op.f('ix_ml_models_id'), table_name='ml_models')
    op.drop_table('ml_models')
    op.drop_index(op.f('ix_rule_templates_name'), table_name='rule_templates')
    op.drop_index(op.f('ix_rule_templates_id'), table_name='rule_templates')
    op.drop_index(op.f('ix_rule_templates_category'),
                  table_name='rule_templates')
    op.drop_table('rule_templates')
    # ### end Alembic commands ###
