"""add_advanced_features_simple

Revision ID: c1d2e3f4g5h6
Revises: 1903bb90c0fb
Create Date: 2025-10-16 16:17:46.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1d2e3f4g5h6'
down_revision: Union[str, None] = '1903bb90c0fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # First, update the existing enum to add new values
    op.execute("ALTER TYPE rulekind ADD VALUE 'statistical_outlier'")
    op.execute("ALTER TYPE rulekind ADD VALUE 'distribution_check'")
    op.execute("ALTER TYPE rulekind ADD VALUE 'correlation_validation'")
    op.execute("ALTER TYPE rulekind ADD VALUE 'ml_anomaly'")

    # Create the new tables
    op.create_table('rule_templates',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('category', sa.String(), nullable=False),
                    sa.Column('template_kind', postgresql.ENUM('missing_data', 'standardization', 'value_list', 'length_range', 'cross_field', 'char_restriction', 'regex',
                                                               'custom', 'statistical_outlier', 'distribution_check', 'correlation_validation', 'ml_anomaly', name='rulekind', create_type=False), nullable=False),
                    sa.Column('template_params', sa.Text(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('usage_count', sa.Integer(), nullable=True),
                    sa.Column('created_by', sa.String(), nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_rule_templates_category'),
                    'rule_templates', ['category'], unique=False)
    op.create_index(op.f('ix_rule_templates_id'),
                    'rule_templates', ['id'], unique=False)
    op.create_index(op.f('ix_rule_templates_name'),
                    'rule_templates', ['name'], unique=False)

    op.create_table('ml_models',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('model_type', sa.String(), nullable=False),
                    sa.Column('version', sa.String(), nullable=False),
                    sa.Column('model_path', sa.String(), nullable=True),
                    sa.Column('model_metadata', sa.Text(), nullable=True),
                    sa.Column('training_dataset_id',
                              sa.String(), nullable=True),
                    sa.Column('training_metrics', sa.Text(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('created_by', sa.String(), nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
                    sa.ForeignKeyConstraint(
                        ['training_dataset_id'], ['datasets.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_ml_models_id'), 'ml_models', ['id'], unique=False)
    op.create_index(op.f('ix_ml_models_name'),
                    'ml_models', ['name'], unique=False)

    op.create_table('rule_suggestions',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('dataset_id', sa.String(), nullable=False),
                    sa.Column('template_id', sa.String(), nullable=True),
                    sa.Column('suggested_rule_name',
                              sa.String(), nullable=False),
                    sa.Column('suggested_params', sa.Text(), nullable=True),
                    sa.Column('confidence_score', sa.Integer(), nullable=True),
                    sa.Column('suggestion_type', sa.String(), nullable=True),
                    sa.Column('reasoning', sa.Text(), nullable=True),
                    sa.Column('is_applied', sa.Boolean(), nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('applied_at', postgresql.TIMESTAMP(
                        timezone=True), nullable=True),
                    sa.Column('applied_by', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['applied_by'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
                    sa.ForeignKeyConstraint(
                        ['template_id'], ['rule_templates.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_rule_suggestions_id'),
                    'rule_suggestions', ['id'], unique=False)

    op.create_table('dataset_profiles',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('dataset_version_id',
                              sa.String(), nullable=False),
                    sa.Column('profile_summary', sa.Text(), nullable=True),
                    sa.Column('column_profiles', sa.Text(), nullable=True),
                    sa.Column('data_quality_score',
                              sa.Integer(), nullable=True),
                    sa.Column('recommendations', sa.Text(), nullable=True),
                    sa.Column('profiling_version', sa.String(), nullable=True),
                    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['dataset_version_id'], [
                        'dataset_versions.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('dataset_version_id')
                    )
    op.create_index(op.f('ix_dataset_profiles_id'),
                    'dataset_profiles', ['id'], unique=False)

    op.create_table('statistical_metrics',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('dataset_version_id',
                              sa.String(), nullable=False),
                    sa.Column('column_name', sa.String(), nullable=False),
                    sa.Column('metric_type', sa.String(), nullable=False),
                    sa.Column('metric_name', sa.String(), nullable=False),
                    sa.Column('metric_value', sa.Integer(), nullable=True),
                    sa.Column('additional_data', sa.Text(), nullable=True),
                    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['dataset_version_id'], [
                        'dataset_versions.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_statistical_metrics_id'),
                    'statistical_metrics', ['id'], unique=False)

    op.create_table('anomaly_scores',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('execution_id', sa.String(), nullable=False),
                    sa.Column('model_id', sa.String(), nullable=False),
                    sa.Column('row_index', sa.Integer(), nullable=False),
                    sa.Column('anomaly_score', sa.Integer(), nullable=False),
                    sa.Column('features_used', sa.Text(), nullable=True),
                    sa.Column('feature_values', sa.Text(), nullable=True),
                    sa.Column('threshold_used', sa.Integer(), nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['execution_id'], ['executions.id'], ),
                    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_anomaly_scores_id'),
                    'anomaly_scores', ['id'], unique=False)

    op.create_table('debug_sessions',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('execution_id', sa.String(), nullable=False),
                    sa.Column('session_name', sa.String(), nullable=False),
                    sa.Column('debug_data', sa.Text(), nullable=True),
                    sa.Column('breakpoints', sa.Text(), nullable=True),
                    sa.Column('variable_snapshots', sa.Text(), nullable=True),
                    sa.Column('created_by', sa.String(), nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
                    sa.ForeignKeyConstraint(
                        ['execution_id'], ['executions.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_debug_sessions_id'),
                    'debug_sessions', ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_debug_sessions_id'), table_name='debug_sessions')
    op.drop_table('debug_sessions')
    op.drop_index(op.f('ix_anomaly_scores_id'), table_name='anomaly_scores')
    op.drop_table('anomaly_scores')
    op.drop_index(op.f('ix_statistical_metrics_id'),
                  table_name='statistical_metrics')
    op.drop_table('statistical_metrics')
    op.drop_index(op.f('ix_dataset_profiles_id'),
                  table_name='dataset_profiles')
    op.drop_table('dataset_profiles')
    op.drop_index(op.f('ix_rule_suggestions_id'),
                  table_name='rule_suggestions')
    op.drop_table('rule_suggestions')
    op.drop_index(op.f('ix_ml_models_name'), table_name='ml_models')
    op.drop_index(op.f('ix_ml_models_id'), table_name='ml_models')
    op.drop_table('ml_models')
    op.drop_index(op.f('ix_rule_templates_name'), table_name='rule_templates')
    op.drop_index(op.f('ix_rule_templates_id'), table_name='rule_templates')
    op.drop_index(op.f('ix_rule_templates_category'),
                  table_name='rule_templates')
    op.drop_table('rule_templates')
    # ### end Alembic commands ###
